version: "3.9"

services: ##everything under this is a containerized service
  backend:
    build: ./backend #build an image
    ports:
      - "5000:5000" #porting host to container
    env_file:
      - .env
    volumes:
      - ./backend:/app #enables live reload
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app #live source code
      - /app/node_modules # 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true ## Add this to hot reload
    depends_on:
      - backend #makes sure back end starts first
    restart: unless-stopped
